name: Build

on:
  push:
    branches:
      - main
      - 'feature/**' # scan any and all feature branches
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: .
          args: >
            "-Dsonar.projectName=Jamie NX SCA"
            -Dsonar.projectKey=jamie-nx-sca
            -Dsonar.sca.enabled=true
            -Dsonar.verbose=true
           # -Dsonar.inclusions=pnpm-lock.yaml
           # -Dssonar.sca.recursiveManifestSearch=false
           # -Dsonar.sca.npmNoResolve=true
           # -Dsonar.sca.exclusions=package.json,Cargo.lock,Cargo.toml,nx-dev/**,packages/**,tools/**,typedoc-theme/**,docs/**